### ISSUE TITLE
Gost CMS Encryption

### ISSUE THREAD

**Issue by Fasjeit** [CryptoPro/corefx#17]

**Comment by AlexeyAKat** [comment]
Did I understand correctly that CMS Encryption is not working now?
The following code throws an exception:

```csharp
var contentInfo = new ContentInfo(msg);
var envelopedCms = new EnvelopedCms(contentInfo);

// myCert, recipientCert - X509Certificate2 objects of Gost certificates
var certsColl = new X509Certificate2Collection(new [] { myCert, recipientCert });
var cmsRecipients = new CmsRecipientCollection(SubjectIdentifierType.IssuerAndSerialNumber, certsColl);

// throws an exception
envelopedCms.Encrypt(cmsRecipients);
```

Exception stack trace:
```
Windows:
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Встречено неверное значение тега ASN1.
   at Internal.Cryptography.Pal.Windows.PkcsPalWindows.EncodeHelpers.CreateCryptMsgHandleToEncode(CmsRecipientCollection recipients, Oid innerContentType, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes)
   at Internal.Cryptography.Pal.Windows.PkcsPalWindows.Encrypt(CmsRecipientCollection recipients, ContentInfo contentInfo, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes)
   at System.Security.Cryptography.Pkcs.EnvelopedCms.Encrypt(CmsRecipientCollection recipients)

Linux:
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Unknown error (0xffffffff)
    at Internal.Cryptography.Pal.Windows.PkcsPalWindows.EncodeHelpers.CreateCryptMsgHandleToEncode(CmsRecipientCollection recipients, Oid innerContentType, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes)
    at Internal.Cryptography.Pal.Windows.PkcsPalWindows.Encrypt(CmsRecipientCollection recipients, ContentInfo contentInfo, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes)
    at System.Security.Cryptography.Pkcs.EnvelopedCms.Encrypt(CmsRecipientCollection recipients)
```

OS: Windows 10 Home 1909, Ubuntu 18.04.4 LTS, .net core 3.1 (SDK 3.1.202, runtime 3.1.4), Crypto-Pro CSP 5.0.11732 KC1 (5.0.11455 on Windows), instruction [Linux.md](https://github.com/CryptoPro/DotnetCoreSampleProject/blob/master/docs/Linux.md), [Windows.md](https://github.com/CryptoPro/DotnetCoreSampleProject/blob/master/docs/Windows.md) was used, corefx ver.3.1.1.241 (4.7.0-dev.20175.1).

**Comment by Fasjeit** [comment]
ms где то поменяло логику, переписав её в методе EncodeKeyTransRecipientInfo
```csharp
private static unsafe CMSG_ENVELOPED_ENCODE_INFO* CreateCmsEnvelopedEncodeInfo(CmsRecipientCollection recipients, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes, HeapBlockRetainer hb)
```

не вижу кода, который бы соотв. коду из старого fw (при этом он раньше вызывался)

```csharp
      if (encryptParam.useCms)
      {
      // похожий код есть в текущей реализации
      }
      // этого кода просто нет
      else
      {
        EnvelopedCms.SetPkcs7RecipientParams(recipients, ref encryptParam, out certContexts);
        envelopedEncodeInfo.rgpRecipients = encryptParam.rgpRecipients.DangerousGetHandle();
      }
```

Не знаю пока, в этом ли причина, но падает в CryptMsgOpenToEncode, флаги все те же, что и в FW.

**Comment by Fasjeit** [comment]
Основная работа по поддержке CMS шифрования тут
https://github.com/CryptoPro/corefx/issues/56
