### ISSUE TITLE
Не работает чтение RSA сертификата из pfx в linux

### ISSUE THREAD

**Issue by Mblkolo** [CryptoPro/corefx#26]
### В чём проблема
При попытке считать сертификат в патченном рантайме получаем либо ошибку `Unknown error (0x80070002)`, либо ошибку сегментации.

### Как воспроизвести
* Выполнить инструкцию по установке под [linux ](https://github.com/CryptoPro/DotnetCoreSampleProject/blob/master/docs/Linux.md), версия 4.7.0-dev.20163.1
* Создать самоподписанный сертификат с помощью [PowerShell ](https://medium.com/the-new-control-plane/generating-self-signed-certificates-on-windows-7812a600c2d8)
* Добавить код чтения сертификата 

Если написать`new X509Certificate2(certName, certPass)`, то падает с ошибкой 
```
Unhandled exception. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Unknown error (0x80070002)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/CertificatePal.Import.cs:line 77
   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/CertificatePal.Import.cs:line 26
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate.cs:line 137
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate.cs:line 118
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate2.cs:line 88
```

Если написать `new X509Certificate2(File.ReadAllBytes(certName), certPass)`, то падает с ошибкой 
```
Ошибка сегментирования
```

Если переложить скомпилированную dll в обычный netcore runtime 3.1, то код выполняется без ошибок.

[reproduce_project.zip](https://github.com/CryptoPro/corefx/files/4721379/reproduce_project.zip)

**Comment by Mblkolo** [comment]
Нашёл, что в файле `System.Security.Cryptography.X509Certificates.csproj` [закомментирована часть файлов](https://github.com/CryptoPro/corefx/blob/755f78082e27a2e59017550f5f1a6486fe1c08bc/src/System.Security.Cryptography.X509Certificates/src/System.Security.Cryptography.X509Certificates.csproj#L363-L381) из папки `Internal/Cryptography/Pal.Unix` и поэтому под linux выполняется код из 
```
Internal/Cryptography/Pal.Windows/CertificatePal.Import.cs
```
 а не из 
```
Internal/Cryptography/Pal.Unix/OpenSslX509CertificateReader.cs
```

В чём здесь задумка?

**Comment by Fasjeit** [comment]
@tolyanich Проверил, действительно не работает с указанной ошибкой. Работа через хранилище - корректная. Отдельный интересный вопрос - что будет если импортировать гостовый, даже если пройдёт дальше - должен же быть ввод пользователя, для ввода информации о контейнере?

@Mblkolo пока можете установить сертификаты в хранилище через утилитку certmgr:
`/opt/cprocsp/bin/amd64/certmgr -install  -pfx -file ps_cert.pfx -store My -pin password1234`

после чего загрузить сертификаты через хранилище.

**Comment by Mblkolo** [comment]
Я уже понял, что вы работаете через CAPILite.

> пока можете установить сертификаты в хранилище через утилитку certmgr

Я как раз по такому пути пошёл, выпустил гостовский сертификат и установил его в хранилище текущего пользователя. Физически наблюдаю по пути `/var/opt/cprocsp/keys/{username}/d89a877f.001` и вижу в списке сертификатов.

```
/opt/cprocsp/bin/amd64/certmgr -list -store My
Certmgr 1.1 (c) "Crypto-Pro",  2007-2019.
program for managing certificates, CRLs and stores

WARNING: Legacy parameter: "-store My"
=============================================================================
1-------
Issuer              : E=support@cryptopro.ru, C=RU, L=Moscow, O=CRYPTO-PRO LLC, CN=CRYPTO-PRO Test Center 2
и т.д.
```

Но не могу получить доступ к сертификату программно. Пробовал через `var store = new X509Store(StoreLocation.LocalMachine)` и подобные комбинации, но `store.Certificates` всегда пустой.

Как под linux загрузить сертификаты через хранилище?

**Comment by tolyanich** [comment]
Попробуйте вот так
`var x509Store = new X509Store(StoreName.My, StoreLocation.CurrentUser);`
  `x509Store.Open(OpenFlags.ReadOnly);`

**Comment by Mblkolo** [comment]
> Попробуйте вот так
> `var x509Store = new X509Store(StoreName.My, StoreLocation.CurrentUser);`
> `x509Store.Open(OpenFlags.ReadOnly);`

Спасибо, флаги помогли. Теперь не могу проверить подпись:
```
        private static void CheckDetachedSign(ContentInfo contentInfo, byte[] signature)
        {
            var signedCms = new SignedCms(contentInfo, true);
            signedCms.Decode(signature);
            signedCms.CheckSignature(true);
        }
```

Падает `CheckSignature` с `Unable to find an entry point named 'CertAddCertificateLinkToStore' in shared library 'libcapi20'.`. Я так понимаю, что CAPILite не реализует `CertAddCertificateLinkToStore`.

```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'CertAddCertificateLinkToStore' in shared library 'libcapi20'.
   at Interop.crypt32.CertAddCertificateLinkToStore(SafeCertStoreHandle hCertStore, SafeCertContextHandle pCertContext, CertStoreAddDisposition dwAddDisposition, IntPtr ppStoreContext)
   at Internal.Cryptography.Pal.StorePal.LinkFromCertificateCollection(X509Certificate2Collection certificates) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/StorePal.Import.cs:line 146
   at Internal.Cryptography.Pal.FindPal..ctor(X509Certificate2Collection findFrom, X509Certificate2Collection copyTo, Boolean validOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/FindPal.cs:line 26
   at Internal.Cryptography.Pal.FindPal.OpenPal(X509Certificate2Collection findFrom, X509Certificate2Collection copyTo, Boolean validOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/FindPal.cs:line 33
   at Internal.Cryptography.Pal.FindPal.FindFromCollection(X509Certificate2Collection coll, X509FindType findType, Object findValue, Boolean validOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/FindPal.cs:line 47
   at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Find(X509FindType findType, Object findValue, Boolean validOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate2Collection.cs:line 125
   at System.Security.Cryptography.Pkcs.SignerInfo.FindSignerCertificate(SubjectIdentifier signerIdentifier, X509Certificate2Collection extraStore) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs:line 468
   at System.Security.Cryptography.Pkcs.SignerInfo.FindSignerCertificate() in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs:line 448
   at System.Security.Cryptography.Pkcs.SignerInfo.get_Certificate() in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs:line 96
   at System.Security.Cryptography.Pkcs.SignerInfo.CheckSignature(X509Certificate2Collection extraStore, Boolean verifySignatureOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs:line 403
   at System.Security.Cryptography.Pkcs.SignedCms.CheckSignatures(SignerInfoCollection signers, X509Certificate2Collection extraStore, Boolean verifySignatureOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 595
   at System.Security.Cryptography.Pkcs.SignedCms.CheckSignature(X509Certificate2Collection extraStore, Boolean verifySignatureOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 578
   at System.Security.Cryptography.Pkcs.SignedCms.CheckSignature(Boolean verifySignatureOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 569
   at InfinitumCertTest.Program.CheckAttachedSign(Byte[] attachedSing) in /home/mblkolo/crypto_pro/run_test/play/Program.cs:line 35
   at InfinitumCertTest.Program.Main(String[] args) in /home/mblkolo/crypto_pro/run_test/play/Program.cs:line 20
```

Является ли текущее поведение ошибочным или есть другой путь проверить подпись?

Попробовал вызывать метод Find из уже загруженной коллекции, но получаю то же самое исключение:
```
            using (var store = new X509Store(StoreName.My, StoreLocation.CurrentUser, OpenFlags.ReadWrite))
            {
                 //Unable to find an entry point named 'CertAddCertificateLinkToStore' in shared library 'libcapi20'.
                 store.Certificates.Find(X509FindType.FindBySubjectName, "sdfsdf", true);
```

Нашёл аналогичную проблему на [форуме](https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=115404#post115404). Не нашёл ответа.

**Comment by tolyanich** [comment]
Решение есть вот тут - [issue 22](https://github.com/CryptoPro/corefx/issues/22)

**Comment by tolyanich** [comment]
После вот этого [коммита](https://github.com/CryptoPro/corefx/commit/f1c59c3b6a3817a591006acb9591b03c39baf303) должен работать конструктор X509Certificate2 с pfx при указании пароля как в string так и в SecureString.
