### ISSUE TITLE
Ошибка при попытке подписать сообщение подписью CMS/PKCS 7

### ISSUE THREAD

**Issue by RakotVT** [CryptoPro/corefx#36]
При попытке подписать строку подписью CMS/PKCS 7 выдается ошибка:

Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Cryptography error
   at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.get_SafeProvHandle()
   at System.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.get_SafeKeyHandle()
   at System.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider..ctor(CspParameters parameters)
   at Internal.Cryptography.Pal.Windows.PkcsPalWindows.GetPrivateKey[T](X509Certificate2 certificate, Boolean silent, Boolean preferNCrypt) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/Windows/PkcsPalWindows.cs:line 266
   at Internal.Cryptography.Pal.Windows.PkcsPalWindows.GetPrivateKeyForSigning[T](X509Certificate2 certificate, Boolean silent) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/Windows/PkcsPalWindows.cs:line 181
   at System.Security.Cryptography.Pkcs.CmsSignature.Gost2012_256CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, Oid& signatureAlgorithm, Byte[]& signatureValue) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSignature.Gost2012_256.cs:line 71
   at System.Security.Cryptography.Pkcs.CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, Oid& oid, ReadOnlyMemory`1& signatureValue) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSignature.cs:line 104
   at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSigner.cs:line 251
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 323
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 274

Проект собирался с версией v3.1.1-cprocsp-preview3.291 по инструкции https://github.com/CryptoPro/DotnetCoreSampleProject/blob/master/docs/Linux.md
OS: Debian 9
КриптоПро 5.0 R2

**Comment by tolyanich** [comment]
А вы можете привести что у вас выводит /opt/cprocsp/bin/amd64/certmgrl -list 
и указать какой сертификат вы использовали в сайнере.

**Comment by RakotVT** [comment]
Certmgr 1.1 (c) "Crypto-Pro", 2007-2020.
Program for managing certificates, CRLs and stores.

1-------
Issuer              : OGRN=1027700071530, INN=007704211201, C=RU, S=77 Москва, L=Москва, STREET="Барыковский пер., д. 4, стр. 2", OU=Удостоверяющий центр, O="ООО ""ТАКСКОМ""", CN="ООО ""ТАКСКОМ"""
Subject             : SN=Перфильев, G=Андрей Валентинович, T=ГЕНЕРАЛЬНЫЙ ДИРЕКТОР, STREET="ПРОСПЕКТ КУТУЗОВСКИЙ, ДОМ 34, СТРОЕНИЕ 14, ЭТ. 2 ПОМ. I КОМН. 51", CN="ООО ""МЕДИЦИНСКИЙ ЦЕНТР АТЛАС""", O="ООО ""МЕДИЦИНСКИЙ ЦЕНТР АТЛАС""", L=Москва г, S=77 г. Москва, C=RU, E=77303hk@host39.taxcom.ru, INN=007730699137, OGRN=5137746244422, SNILS=14560897589
Serial              : 0x01C293920021ABF1884F8C2197DDAA8A1D
SHA1 Hash           : b386ad647984fafd6df122f952b6e9455cae306c
SubjKeyID           : 0594b754496ff5273bf6790a83fc5b66a4480fe4
Signature Algorithm : ГОСТ Р 34.11-2012/34.10-2012 256 бит
PublicKey Algorithm : ГОСТ Р 34.10-2012 (512 bits)
Not valid before    : 12/12/2019  08:43:40 UTC
Not valid after     : 12/12/2020  08:53:40 UTC
PrivateKey Link     : Yes
Container           : HDIMAGE\\perfilev.000\0366
Provider Name       : Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider
Provider Info       : Provider Type: 80, Key Spec: 1, Flags: 0x0
OCSP URL            : http://ocsp2012.taxcom.ru/ocsp/ocsp.srf
CA cert URL         : http://crl.taxcom.ru/88afaef6252df4d92cf50f967a14fa1189b7c8a4.crt
CDP                 : http://crl.taxcom.ru/88afaef6252df4d92cf50f967a14fa1189b7c8a4.crl
Extended Key Usage  : 1.3.6.1.5.5.7.3.2 Проверка подлинности клиента
                      1.3.6.1.5.5.7.3.4 Защищенная электронная почта
2-------
Issuer              : E=dit@minsvyaz.ru, C=RU, S=77 Москва, L=г. Москва, STREET="улица Тверская, дом 7", O=Минкомсвязь России, OGRN=1047702026701, INN=007710474375, CN=Минкомсвязь России
Subject             : E=dit@minsvyaz.ru, C=RU, S=77 Москва, L=г. Москва, STREET="улица Тверская, дом 7", O=Минкомсвязь России, OGRN=1047702026701, INN=007710474375, CN=Минкомсвязь России
Serial              : 0x4E6D478B26F27D657F768E025CE3D393
SHA1 Hash           : 4bc6dc14d97010c41a26e058ad851f81c842415a
SubjKeyID           : c254f1b46bd44cb7e06d36b42390f1fec33c9b06
Signature Algorithm : ГОСТ Р 34.11-2012/34.10-2012 256 бит
PublicKey Algorithm : ГОСТ Р 34.10-2012 (512 bits)
Not valid before    : 06/07/2018  12:18:06 UTC
Not valid after     : 01/07/2036  12:18:06 UTC
PrivateKey Link     : No
3-------
Issuer              : E=dit@minsvyaz.ru, C=RU, S=77 Москва, L=г. Москва, STREET="улица Тверская, дом 7", O=Минкомсвязь России, OGRN=1047702026701, INN=007710474375, CN=Минкомсвязь России
Subject             : OGRN=1027700071530, INN=007704211201, C=RU, S=77 Москва, L=Москва, STREET="Барыковский пер., д. 4, стр. 2", OU=Удостоверяющий центр, O="ООО ""ТАКСКОМ""", CN="ООО ""ТАКСКОМ"""
Serial              : 0x00B04EC70100000000031C
SHA1 Hash           : 5953e0932448fb4317db5affd2c5a814db96fe98
SubjKeyID           : 88afaef6252df4d92cf50f967a14fa1189b7c8a4
Signature Algorithm : ГОСТ Р 34.11-2012/34.10-2012 256 бит
PublicKey Algorithm : ГОСТ Р 34.10-2012 (512 bits)
Not valid before    : 24/10/2019  13:00:54 UTC
Not valid after     : 24/10/2034  13:00:54 UTC
PrivateKey Link     : No
CA cert URL         : http://reestr-pki.ru/cdp/guc_gost12.crt
CDP                 : http://reestr-pki.ru/cdp/guc_gost12.crl
CDP                 : http://company.rt.ru/cdp/guc_gost12.crl
CDP                 : http://rostelecom.ru/cdp/guc_gost12.crl

[ErrorCode: 0x00000000]

Используется первый из списка, поиск его производится по серийному номеру

**Comment by RakotVT** [comment]
Тот же сервис с тем же сертификатом на windows server работает корректно

**Comment by maxdm** [comment]
А что в syslog? Последние версии CSP пишут об ошибках.

**Comment by RakotVT** [comment]
Подскажите, куда логи пишется, я не нашел их

**Comment by maxdm** [comment]
journalctl повзоляет просматривать логи на Debian.

**Comment by tolyanich** [comment]
1. Сертификаты 2 и 3 не должны стоят в хранилище My. Они должны стоять в хранилище CA если это сертификаты промежуточных УЦ или в root если это сертификаты корневых УЦ.
2. Подскажите как вы сертификат получаете которые вы передаете в signer. Путем поиска по хранилищу или чтение из файла?

**Comment by RakotVT** [comment]
Сначала импортировал в хранилище криптопро pfx /opt/cprocsp/bin/amd64/certmgr -inst -store umy -pfx -file ~/dist/cryptopro/111.pfx , затем методом x509store.find по серийному номеру осуществляю поиск
```
            var myStore = new X509Store(StoreName.My, StoreLocation.CurrentUser);
            myStore.Open(OpenFlags.ReadOnly);
            var certSerial = _configuration["Signature:CertSerial"];
            var certColl = myStore.Certificates.Find(X509FindType.FindBySerialNumber, certSerial, false);
```

**Comment by tolyanich** [comment]
Должно работать. 
А можете тогда открыть /etc/opt/cprocsp/config64.ini, найти там секцию debug вписать для модулей capi10, capi20 уровень логирования 0x3f. Запустить ваш пример и приложить лог. Лог должен быть или в /var/log/messeges(syslog,authlog) в зависимости от настройки syslog.

**Comment by RakotVT** [comment]
Вывод отфильтрован по capi (sudo cat /var/log/syslog | grep capi)
[logs.log](https://github.com/CryptoPro/corefx/files/5536292/logs.log)

**Comment by maxdm** [comment]
Не очень хорошее имя контейнера. Какое было исходное?
![image](https://user-images.githubusercontent.com/6984595/99065693-d0124300-25b8-11eb-8271-bed1c7101856.png)

**Comment by tolyanich** [comment]
Пока мы изучаем лог, можете проверить ваш пример с последней сборкой?
https://ci.appveyor.com/project/CryptoPro/corefx/builds/36151101/job/7eu6nvm72bnm7ps1/artifacts

**Comment by RakotVT** [comment]
К сожалению, без изменений

**Comment by RakotVT** [comment]
> 
> 
> Не очень хорошее имя контейнера. Какое было исходное?
> ![image](https://user-images.githubusercontent.com/6984595/99065693-d0124300-25b8-11eb-8271-bed1c7101856.png)

REGISTRY\\\perfilev_007730699137_12.12.19_11.50.30 - копия

в Дебиан \\\\.\HDIMAGE\perfilev_007730699137_12.12.19_11.50.30 - копия

**Comment by RakotVT** [comment]
Сейчас сделал тестовый сертификат http://testgost2012.cryptopro.ru/certsrv/
Имя контейнера получилось вроде как нормальное, ошибка не ушла

Issuer              : OGRN=1234567890123, INN=001234567890, STREET=ул. Сущёвский вал д. 18, C=RU, S=г. Москва, L=Москва, O="ООО ""КРИПТО-ПРО""", CN="Тестовый УЦ ООО ""КРИПТО-ПРО"""
Subject             : E=esia-test2012-sign@email.com, CN=esia-test2012-sign, OU=R&D, O=spargo, L=Moscow, C=RU
Serial              : 0x7C000167DC3518734979DA6DE10001000167DC
SHA1 Hash           : f269566b9263bc807ef05e6e4ba31dc11b3fc2b0
SubjKeyID           : 177c11ea8e89ba09f590da5364ee85da72e96d6d
Signature Algorithm : ГОСТ Р 34.11-2012/34.10-2012 256 бит
PublicKey Algorithm : ГОСТ Р 34.10-2012 (512 bits)
Not valid before    : 13/11/2020  13:45:05 UTC
Not valid after     : 13/02/2021  13:55:05 UTC
PrivateKey Link     : Yes
Container           : HDIMAGE\\de5396da.000\E74C
Provider Name       : Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider
Provider Info       : Provider Type: 80, Key Spec: 1, Flags: 0x0
CA cert URL         : http://testgost2012.cryptopro.ru/CertEnroll/root2018.crt
OCSP URL            : http://testgost2012.cryptopro.ru/ocsp2012g/ocsp.srf
OCSP URL            : http://testgost2012.cryptopro.ru/ocsp2012gst/ocsp.srf
CDP                 : http://testgost2012.cryptopro.ru/CertEnroll/!0422!0435!0441!0442!043e!0432!044b!0439%20!0423!0426%20!041e!041e!041e%20!0022!041a!0420!0418!041f!0422!041e-!041f!0420!041e!0022(1).crl
Extended Key Usage  : 1.3.6.1.5.5.7.3.3 Подписывание кода

**Comment by tolyanich** [comment]
Можно тогда вас попросить сделать мелкий пример на котором у вас воспроизводится ошибка и приложить его в запрос. Проверим у себя.

**Comment by RakotVT** [comment]
Сделал демку, запуск dotnet SignerDemo.dll 7C000167DC3518734979DA6DE10001000167DC SGVsbG8gV29ybGQ=
где первый параметр - серийный номер сертификата, второй параметр - base64 строка для подписи
Перед сборкой зависимости надо разложить по папкам в корне проекта 
рантайм: \lib\runtime\linux-x64\ 
пакеты: \lib\packages\linux-x64\
сборки NetStandard из репозитория NetStandard.Library: \lib\netstandard.library (Они на пребилд событии копируются в кеш nuget и очищаются на постбилд событии, если собирать на линукс машине, то надо поправить пути в этих событиях)
Еще в проект добавлен профиль публикации на linux
[SignerDemo.zip](https://github.com/CryptoPro/corefx/files/5545543/SignerDemo.zip)

**Comment by tolyanich** [comment]
Спасибо за пример. У нас воспроизвелась ваша ошибка когда имя контейнера содержит русские буквы. Но при имени контейнера исключительно из латиницы пример отрабатывает и подпись создается. Можете проверить еще раз у себя на контейнере из английских букв? Убедитесь что вы заменили в примере серийник для сертификата.

**Comment by RakotVT** [comment]
У меня сейчас такой набор сертификатов на сервере установлен 
<details>
<summary>Сертификатры</summary>

Issuer              : OGRN=1234567890123, INN=001234567890, STREET=ул. Сущёвский вал д. 18, C=RU, S=г. Москва, L=Москва, O="ООО ""КРИПТО-ПРО""", CN="Тестовый УЦ ООО ""КРИПТО-ПРО"""
Subject             : E=esia-test2012-sign@email.com, CN=esia-test2012-sign, OU=R&D, O=spargo, L=Moscow, C=RU
Serial              : 0x7C000167DC3518734979DA6DE10001000167DC
SHA1 Hash           : f269566b9263bc807ef05e6e4ba31dc11b3fc2b0
SubjKeyID           : 177c11ea8e89ba09f590da5364ee85da72e96d6d
Signature Algorithm : ГОСТ Р 34.11-2012/34.10-2012 256 бит
PublicKey Algorithm : ГОСТ Р 34.10-2012 (512 bits)
Not valid before    : 13/11/2020  13:45:05 UTC
Not valid after     : 13/02/2021  13:55:05 UTC
PrivateKey Link     : Yes
Container           : HDIMAGE\\de5396da.000\E74C
Provider Name       : Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider
Provider Info       : Provider Type: 80, Key Spec: 1, Flags: 0x0
CA cert URL         : http://testgost2012.cryptopro.ru/CertEnroll/root2018.crt
OCSP URL            : http://testgost2012.cryptopro.ru/ocsp2012g/ocsp.srf
OCSP URL            : http://testgost2012.cryptopro.ru/ocsp2012gst/ocsp.srf
CDP                 : http://testgost2012.cryptopro.ru/CertEnroll/!0422!0435!0441!0442!043e!0432!044b!0439%20!0423!0426%20!041e!041e!041e%20!0022!041a!0420!0418!041f!0422!041e-!041f!0420!041e!0022(1).crl
Extended Key Usage  : 1.3.6.1.5.5.7.3.3 Подписывание кода


Issuer              : E=support@cryptopro.ru, C=RU, L=Moscow, O=CRYPTO-PRO LLC, CN=CRYPTO-PRO Test Center 2
Subject             : E=esia-test-sign@email.com, CN=esia-test-sign, OU=R&D, O=spargo, L=Moscow, C=RU
Serial              : 0x12004BF0C2A52E7723DFE33A060001004BF0C2
SHA1 Hash           : 9f4e5280d1c5c6fac5a402624c98e771b43bf306
SubjKeyID           : fd8209e77d705904ea3feec6798aff06a200f289
Signature Algorithm : ГОСТ Р 34.11/34.10-2001
PublicKey Algorithm : ГОСТ Р 34.10-2012 (512 bits)
Not valid before    : 13/11/2020  13:47:48 UTC
Not valid after     : 13/02/2021  13:57:48 UTC
PrivateKey Link     : Yes
Container           : HDIMAGE\\f9029a69.000\B146
Provider Name       : Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider
Provider Info       : Provider Type: 80, Key Spec: 1, Flags: 0x0
CA cert URL         : http://testca.cryptopro.ru/CertEnroll/test-ca-2014_CRYPTO-PRO%20Test%20Center%202(1).crt
OCSP URL            : http://testca.cryptopro.ru/ocsp/ocsp.srf
CDP                 : http://testca.cryptopro.ru/CertEnroll/CRYPTO-PRO%20Test%20Center%202(1).crl
Extended Key Usage  : 1.3.6.1.5.5.7.3.3 Подписывание кода


Issuer              : OGRN=1027700071530, INN=007704211201, C=RU, S=77 Москва, L=Москва, STREET="Барыковский пер., д. 4, стр. 2", OU=Удостоверяющий центр, O="ООО ""ТАКСКОМ""", CN="ООО ""ТАКСКОМ"""
Subject             : SN=Перфильев, G=Андрей Валентинович, T=ГЕНЕРАЛЬНЫЙ ДИРЕКТОР, STREET="ПРОСПЕКТ КУТУЗОВСКИЙ, ДОМ 34, СТРОЕНИЕ 14, ЭТ. 2 ПОМ. I КОМН. 51", CN="ООО ""МЕДИЦИНСКИЙ ЦЕНТР АТЛАС""", O="ООО ""МЕДИЦИНСКИЙ ЦЕНТР АТЛАС""", L=Москва г, S=77 г. Москва, C=RU, E=77303hk@host39.taxcom.ru, INN=007730699137, OGRN=5137746244422, SNILS=14560897589
Serial              : 0x01C293920021ABF1884F8C2197DDAA8A1D
SHA1 Hash           : b386ad647984fafd6df122f952b6e9455cae306c
SubjKeyID           : 0594b754496ff5273bf6790a83fc5b66a4480fe4
Signature Algorithm : ГОСТ Р 34.11-2012/34.10-2012 256 бит
PublicKey Algorithm : ГОСТ Р 34.10-2012 (512 bits)
Not valid before    : 12/12/2019  08:43:40 UTC
Not valid after     : 12/12/2020  08:53:40 UTC
PrivateKey Link     : Yes
Container           : HDIMAGE\\pfx-8d5b.000\AF3F
Provider Name       : Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider
Provider Info       : Provider Type: 80, Key Spec: 1, Flags: 0x0
OCSP URL            : http://ocsp2012.taxcom.ru/ocsp/ocsp.srf
CA cert URL         : http://crl.taxcom.ru/88afaef6252df4d92cf50f967a14fa1189b7c8a4.crt
CDP                 : http://crl.taxcom.ru/88afaef6252df4d92cf50f967a14fa1189b7c8a4.crl
Extended Key Usage  : 1.3.6.1.5.5.7.3.2 Проверка подлинности клиента
                      1.3.6.1.5.5.7.3.4 Защищенная электронная почта
</details>

На вид везде контейнеры с английскими буквами, ошибка на всех трех сертификатах есть. Не могли бы вы показать как правильно импортировать pfx и crt файлы сертификата, может мы что-то неверно делали?

**Comment by tolyanich** [comment]
/opt/cprocsp/bin/amd64/csptest -keyset -enum_c -verifyc -fqcn 
вот так можно посмотреть полные имена контейнеров

**Comment by RakotVT** [comment]
\\\\.\HDIMAGE\de5396da1-2cd2-47a9-84cb-ac0e833bdd4
\\\\.\HDIMAGE\pfx-8d5bfdc7-c03e-af8a-dfb9-0c0ea311460d
\\\\.\HDIMAGE\f1f3fb698-23b7-5483-8626-a6ef8c49535
\\\\.\HDIMAGE\f9029a692-3b43-6c2d-4ac6-6241bd248c5
Список контейнеров, тот что был с русскими буквами я удалил

**Comment by tolyanich** [comment]
А можете лог приложить от вашего примера с новым контейнером, там где видны операции криптопровайдера.

**Comment by RakotVT** [comment]
```
Hello World!
Cetificate Serial 7C000167DC3518734979DA6DE10001000167DC
Message to sign: SGVsbG8gV29ybGQ=
Всего сертификатов 3 в cMy
Сертификат найден
Сертификат найден. Серийный номер 7C000167DC3518734979DA6DE10001000167DC. Субъект C=RU, L=Moscow, O=spargo, OU=R&D, CN=esia-test2012-sign, E=esia-test2012-sign@email.com
Cryptography error

   at Internal.NativeCrypto.CapiHelper.SignValue(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash)
   at System.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.SignHash(Byte[] rgbHash)
   at System.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.SignHash(Byte[] rgbHash, HashAlgorithmName hashAlgName)
   at System.Security.Cryptography.Gost3410_2012_256.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, Int32& bytesWritten)
   at System.Security.Cryptography.Pkcs.CmsSignature.Gost2012_256CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, Oid& signatureAlgorithm, Byte[]& signatureValue) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSignature.Gost2012_256.cs:line 87
   at System.Security.Cryptography.Pkcs.CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, Oid& oid, ReadOnlyMemory`1& signatureValue) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSignature.cs:line 104
   at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSigner.cs:line 251
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 323
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 274
   at SignerDemo.Program.SignMessage(String message, String certSerial) in /home/rakot/repo/signerdemo/SignerDemo/Program.cs:line 55
Unhandled exception. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Cryptography error
   at Internal.NativeCrypto.CapiHelper.SignValue(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash)
   at System.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.SignHash(Byte[] rgbHash)
   at System.Security.Cryptography.Gost3410_2012_256CryptoServiceProvider.SignHash(Byte[] rgbHash, HashAlgorithmName hashAlgName)
   at System.Security.Cryptography.Gost3410_2012_256.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, Int32& bytesWritten)
   at System.Security.Cryptography.Pkcs.CmsSignature.Gost2012_256CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, Oid& signatureAlgorithm, Byte[]& signatureValue) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSignature.Gost2012_256.cs:line 87
   at System.Security.Cryptography.Pkcs.CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, Oid& oid, ReadOnlyMemory`1& signatureValue) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSignature.cs:line 104
   at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSigner.cs:line 251
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer, Boolean silent) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 323
   at System.Security.Cryptography.Pkcs.SignedCms.ComputeSignature(CmsSigner signer) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 274
   at SignerDemo.Program.SignMessage(String message, String certSerial) in /home/rakot/repo/signerdemo/SignerDemo/Program.cs:line 55
   at SignerDemo.Program.Main(String[] args) in /home/rakot/repo/signerdemo/SignerDemo/Program.cs:line 16
```

**Comment by tolyanich** [comment]
Тут  у вас совсем другая ошибка. Сам контейнер у вас открылся.  Можете еще лог от syslog приложить?

**Comment by RakotVT** [comment]
[syslog.log](https://github.com/CryptoPro/corefx/files/5553675/syslog.log)
Да, я обратил на это внимание, уже лучше, она видимо вылечилась удалением того контейнера

**Comment by tolyanich** [comment]
Тут беда в том что у вас ключ с пинкодом. А .NET Core при открытии ключа запрещает показывать окна. К сожалению, интерфейс MS по передачи сертификата в класс Signer не подразумевает передачи пин кода. По сертификату вы можете получить параметры для создания CSPParameters и передать пинкод туда, далее через него уже создать signer и дальше ...
Либо можно убрать пинкод с ключа. 
Или можно попробовать создать обьект сертификата из pfx не сохраняя его в хранилище
var crt = new X509Certificate2("path to pfx", passwd, X509KeyStorageFlags.CspNoPersistKeySet);

**Comment by RakotVT** [comment]
`Либо можно убрать пинкод с ключа.`
То есть при импорте в хранилище оставить его без пароля?
Сейчас попробую оба варианта

**Comment by RakotVT** [comment]
Все заработало с сертификатом, импорированным без пароля, тогда еще вопрос, как переименовать контейнер?
