### ISSUE TITLE
ошибка проверки открепленной подписи

### ISSUE THREAD

**Issue by mshamito** [CryptoPro/corefx#55]
ubuntu 22.04
при проверке только что созданной открепленной подписи возвращается ошибка

```
Unhandled exception. System.Security.Cryptography.CryptographicException: The hash value is not correct.
   at System.Security.Cryptography.Pkcs.SignerInfo.PrepareDigest(Boolean compatMode) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs:line 589
   at System.Security.Cryptography.Pkcs.SignerInfo.VerifySignature(CmsSignature signatureProcessor, X509Certificate2 certificate, Boolean compatMode) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs:line 698
   at System.Security.Cryptography.Pkcs.SignerInfo.Verify(X509Certificate2Collection extraStore, X509Certificate2 certificate, Boolean verifySignatureOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs:line 647
   at System.Security.Cryptography.Pkcs.SignerInfo.CheckSignature(X509Certificate2Collection extraStore, Boolean verifySignatureOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs:line 415
   at System.Security.Cryptography.Pkcs.SignedCms.CheckSignatures(SignerInfoCollection signers, X509Certificate2Collection extraStore, Boolean verifySignatureOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 595
   at System.Security.Cryptography.Pkcs.SignedCms.CheckSignature(X509Certificate2Collection extraStore, Boolean verifySignatureOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 578
   at System.Security.Cryptography.Pkcs.SignedCms.CheckSignature(Boolean verifySignatureOnly) in /home/appveyor/projects/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs:line 569
   at cms_raw.Program.Main(String[] args)
```

на http://dss.cryptopro.ru/Verify/Verify/ проверка проходит успешно.
создание и проверка присоединенной подписи также проходит успешно

``` csharp
            bool detached = true;
            SignedCms verifySign = detached ? 
                new SignedCms(new ContentInfo(msg)) : 
                new SignedCms();
            verifySign.Decode(sign);
            verifySign.CheckSignature(true);
```

**Comment by Fasjeit** [comment]
Попробуйте явно указать тип подписи при проверке
```csharp
bool detached = true;
SignedCms verifySign = detached ? 
    new SignedCms(new ContentInfo(msg), detached) : // changes here, explicit detached signature
    new SignedCms();
verifySign.Decode(sign);
verifySign.CheckSignature(true);
```

**Comment by mshamito** [comment]
так работает! спасибо!
